export const EPISODES_SEARCH = 'EPISODES_SEARCH';
export const EPISODES_SEARCH_SUCCESS = 'EPISODES_SEARCH_SUCCESS';

export const EPISODE_FETCH = 'EPISODE_FETCH';
export const EPISODE_FETCH_SUCCESS = 'EPISODE_FETCH_SUCCESS';
