export const SHOWS_SEARCH = 'SHOWS_SEARCH';
export const SHOWS_SEARCH_SUCCESS = 'SHOWS_SEARCH_SUCCESS';

export const SHOW_FETCH = 'SHOW_FETCH';
export const SHOW_FETCH_SUCCESS = 'SHOW_FETCH_SUCCESS';
